name: stack_tracker
description: "Track your gold, silver, platinum, and palladium investments with ease."
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.1+11

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  http: ^1.2.1
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  intl: ^0.18.1
  google_mobile_ads: ^5.1.0
  fl_chart: ^0.63.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter:
  uses-material-design: true
